export const cvContent = {
  identity: {
    name: "Ricardo Jorge",
    title: "AI Product Engineer",
    location: "Lisbon, Portugal",
    email: "ricardojorgexyz@gmail.com",
    cv: { label: "cv.rj11.io", href: "https://cv.rj11.io/" },
    website: { label: "rj11.io", href: "https://rj11.io/" },
    github: { label: "github.com/rj11io", href: "https://github.com/rj11io" },
    linkedin: {
      label: "linkedin.com/in/rj11io",
      href: "https://linkedin.com/in/rj11io",
    },
  },
  profile: {
    summary:
      "AI Product Engineer with a decade of professional TypeScript experience, building on React since 2016 and Next.js since 2018. I build data-heavy products and AI workflows from the ground up, often as the first frontend hire responsible for architecture, tooling, component libraries, infrastructure, and delivery pipelines.",
    detail:
      "My work spans dashboards, product platforms, and proprietary data explorers for cybersecurity, crypto, gaming, and early-stage B2B products. I have built with AI since the first releases of Copilot and ChatGPT, moving from prompt and context engineering to open-source skills, agent harnesses, and automations.",
  },
  capabilities: [
    {
      label: "Product stack",
      items: [
        "TypeScript",
        "React.js",
        "Next.js",
        "AI SDK",
        "Convex",
        "Playwright",
        "Vercel",
      ],
    },
    {
      label: "AI engineering",
      items: [
        "Agent Automations",
        "Custom Agent Skills",
        "Harness Engineering",
        "Codex",
        "Claude Code",
        "n8n",
      ],
    },
    {
      label: "Interface and data",
      items: [
        "Tailwind CSS",
        "shadcn/ui",
        "Material-UI",
        "Design Systems",
        "Storybook",
        "Refactoring UI",
        "Dashboards",
        "Data Visualisation (d3, Recharts, Nivo)",
        "Web Scraping",
        "Data Enrichment",
      ],
    },
    {
      label: "Delivery and foundations",
      items: [
        "Team and Project Management",
        "End-to-End Product Engineering",
        "Product Design",
        "Agile Methodologies",
        "JavaScript",
        "Node.js",
        "HTML5",
        "CSS",
        "Git",
        "GitHub Actions",
        "REST APIs",
        "CI/CD",
        "Testing",
      ],
    },
  ],
  projects: [
    {
      name: "11io",
      urlLabel: "rj11.io",
      href: "https://rj11.io/",
      dates: "2025 - Present",
      description: "Personal brand for B2B freelancing",
      compact: false,
    },
    {
      name: "11ai",
      urlLabel: "ai.rj11.io",
      href: "https://ai.rj11.io/",
      dates: "2026 - Present",
      description: "Open source AI skills, plugins, and workflows",
      compact: false,
    },
    {
      name: "11bench",
      urlLabel: "bench.rj11.io",
      href: "https://bench.rj11.io/",
      dates: "2026 - Present",
      description: "Open source AI benchmarks",
      compact: false,
    },
    {
      name: "Modern Github",
      urlLabel: "github.com/rj11io",
      href: "https://github.com/rj11io",
      dates: "2023 - Present",
      description: "Modern Github for AI open-source projects",
      compact: true,
    },
    {
      name: "Legacy Github",
      urlLabel: "github.com/ricardojrmcom",
      href: "https://github.com/ricardojrmcom",
      dates: "2020 - 2023",
      description: "Legacy Github with open-source code produced 2020-2023",
      compact: true,
    },
  ],
  experience: [
    {
      id: "rj11io",
      role: "AI Product Engineer",
      employer: "rj11io",
      employerHref: "https://rj11.io/",
      context: "B2B / Remote",
      dates: "Mar 2025 - Present",
      intro:
        "Hands-on AI product engineering for multiple early-stage startups, building projects from the ground up.",
      bullets: [
        "Built AI data extraction from PDFs, AI SEO analytics, a GenAI dermatopathology portal, real estate platform work, AI chats, and custom GPT experiences.",
        "Built cybersecurity dashboards, proprietary data explorers, AI scraping agents, n8n workflows, and AI agent harnesses, skills, and automations.",
      ],
    },
    {
      id: "hunt",
      role: "Product / Datavis Engineer",
      employer: "Hunt Intelligence, Inc.",
      employerHref: "https://hunt.io/",
      context: "B2B / Remote",
      dates: "Apr 2024 - Mar 2025",
      intro:
        "Built a modern TypeScript and Next.js product codebase with shadcn/ui, Vercel environments, Playwright, GitHub Actions, and automated Slack release changelogs.",
      bullets: [
        "Built custom threat-intelligence visualisations including the IP History Widget, and core modules AttackCapture™ and HuntSQL™.",
        "Built an OpenAPI documentation platform that enriched raw metadata and shipped a friendlier, more intuitive alternative to Swagger.",
      ],
    },
    {
      id: "omega",
      role: "Senior Frontend Engineer -> Team Lead",
      employer: "OMEGA Systems",
      employerHref: "https://omegasys.eu/",
      context: "Remote",
      dates: "Jun 2023 - Apr 2024",
      intro:
        "Built CORE5, the next generation of OMEGA's iGaming platform management system with TypeScript and React; promoted to lead the frontend team.",
      bullets: [
        "Built data visualisation for Main and Social dashboards, report and configuration views, a localisation module, and an internal Tab System UI.",
        "Built the new-developer onboarding experience and standards for tickets, documentation, remote/async workflows, and Definition of Done; gave weekly TED talks.",
      ],
    },
    {
      id: "phantasma",
      role: "Senior Frontend Engineer",
      employer: "Phantasma Chain",
      employerHref: "https://phantasma.info/",
      context: "Remote",
      dates: "Jan 2022 - May 2023",
      intro:
        "Built the frontend monorepo for new tools and apps, the Phantasma UI Storybook, and Phantasma Explorer.",
      bullets: [
        "Set up Playwright tests, GitHub Actions CI, and Vercel CD; contributed improvements to the Phantasma TypeScript SDK.",
        "Built in-house tooling for a React SDK hook, localisation, white-label theming, environment configs, and API/scripts/hooks.",
      ],
    },
    {
      id: "binaryedge",
      role: "Frontend Lead",
      employer: "BinaryEdge / Coalition, Inc.",
      employerHref: "https://coalitioninc.com/",
      context: "Remote",
      dates: "Feb 2020 - Oct 2021",
      intro:
        "Started as a solo frontend engineer and grew a team focused on customer-facing security apps and internal tools; introduced React, TypeScript, Next.js, and micro frontends.",
      bullets: [
        "Led Attack Surface Monitoring on the BinaryEdge Portal, later integrated into Coalition Explorer and Coalition Control; led the component library and data visualisations.",
        "Migrated frontend CI/CD from Drone to GitHub Actions, improving pipelines, environments, and developer experience.",
      ],
    },
  ],
  earlier: [
    {
      role: "Fullstack Engineer, Co-Founder",
      employer: "Glaiveware",
      place: "Lisbon / Remote",
      dates: "Mar 2018 - Dec 2019",
      note: "Bespoke web apps; project and business management.",
    },
    {
      role: "React Native Developer",
      employer: "Sycret.ink",
      place: "Neuchâtel, Switzerland / Remote",
      dates: "Jan 2017 - Dec 2017",
      note: "Contract mobile chat app with end-to-end encryption; team of three.",
    },
    {
      role: "Full Stack JavaScript Developer",
      employer: "American Heart Association",
      place: "Remote",
      dates: "Sep 2016 - Nov 2016",
      note: "React and Node admin dashboard for a Kinect integration.",
    },
    {
      role: "Frontend Developer",
      employer: "NextBitt",
      place: "Lisbon",
      dates: "Oct 2015 - Jul 2016",
      note: "Analytics dashboards, reporting, auditing, management tools, and data visualisation.",
    },
    {
      role: "Java Developer",
      employer: "Science4you",
      place: "Lisbon",
      dates: "Jan 2015 - Mar 2015",
      note: "Internship building a Java/MySQL online-store management system, reports, and automated email workflows.",
    },
  ],
  education: {
    title: "IT Systems Management and Programming",
    school: "Escola Profissional de Tecnologia Digital",
    place: "Lisbon",
    dates: "2013 - 2016",
    localTitle: "Técnico de Gestão e Programação de Sistemas Informáticos",
  },
  beyondWork: [
    "Started coding by modding and reverse-engineering games and consoles; built a fighting game with the MUGEN engine and ran dedicated servers for Counter-Strike and Minecraft.",
    "Placed second nationally and reached the final four of the 2008 robotics world cup in China with LEGO Mindstorms.",
  ],
} as const
