import type { DemoWorkspace, Position, ScenarioSnapshot } from "./types"

const clonePosition = (
  position: Position,
  overrides: Partial<Position> = {}
): Position => ({
  ...position,
  ...overrides,
})

const basePositions = {
  safeEthUsdc: {
    id: "safe-eth-usdc",
    asset: "USDC",
    issuer: "Circle",
    chain: "Ethereum",
    venue: "Safe Primary",
    wallet: "Ops Safe",
    walletType: "Safe",
    kind: "spot",
    valueUsd: 3_350_000,
    change24hPct: -0.1,
    liquidityBucket: "T+0",
    riskLevel: "low",
    notes: "Native operating reserve used for payroll and grants.",
    tags: ["stablecoin", "circle", "liquid"],
    source: "Seeded Safe balance",
    updatedAt: "Jul 16, 2026 09:32 UTC",
  },
  safeBaseUsdc: {
    id: "safe-base-usdc",
    asset: "USDC",
    issuer: "Circle",
    chain: "Base",
    venue: "Base Ops Safe",
    wallet: "Base Ops",
    walletType: "Safe",
    kind: "spot",
    valueUsd: 1_180_000,
    change24hPct: -0.2,
    liquidityBucket: "T+0",
    riskLevel: "medium",
    notes: "Fast payout lane, but dependent on secondary chain liquidity.",
    tags: ["stablecoin", "circle", "liquid", "secondary-chain"],
    source: "Seeded Safe balance",
    updatedAt: "Jul 16, 2026 09:32 UTC",
  },
  tronUsdt: {
    id: "tron-usdt-float",
    asset: "USDT",
    issuer: "Tether",
    chain: "Tron",
    venue: "Market-Maker Float",
    wallet: "Falcon Float",
    walletType: "Watch-only",
    kind: "spot",
    valueUsd: 1_620_000,
    change24hPct: 0,
    liquidityBucket: "T+0",
    riskLevel: "high",
    notes: "High throughput settlement float with counterparty and screening sensitivity.",
    tags: ["stablecoin", "tether", "liquid", "breach", "counterparty"],
    source: "Seeded watch-only balance",
    updatedAt: "Jul 16, 2026 09:28 UTC",
  },
  solUsdc: {
    id: "solana-usdc-payments",
    asset: "USDC",
    issuer: "Circle",
    chain: "Solana",
    venue: "Payments Wallet",
    wallet: "Solana Payouts",
    walletType: "Watch-only",
    kind: "spot",
    valueUsd: 880_000,
    change24hPct: -0.1,
    liquidityBucket: "T+0",
    riskLevel: "medium",
    notes: "Used for vendor and contributor payouts with fast finality.",
    tags: ["stablecoin", "circle", "liquid", "secondary-chain"],
    source: "Seeded watch-only balance",
    updatedAt: "Jul 16, 2026 09:27 UTC",
  },
  susdsVault: {
    id: "susds-vault",
    asset: "sUSDS",
    issuer: "Sky",
    chain: "Ethereum",
    venue: "Sky Savings",
    wallet: "Yield Safe",
    walletType: "Safe",
    kind: "vault",
    valueUsd: 2_240_000,
    change24hPct: 0.1,
    liquidityBucket: "T+1",
    riskLevel: "medium",
    notes: "Yield sleeve with redemption latency and governance dependency.",
    tags: ["stablecoin", "protocol", "yield"],
    source: "Seeded ERC-4626 position",
    updatedAt: "Jul 16, 2026 09:25 UTC",
    underlying: "USDS",
  },
  sdaiVault: {
    id: "sdai-vault",
    asset: "sDAI",
    issuer: "Sky",
    chain: "Ethereum",
    venue: "Spark",
    wallet: "Yield Safe",
    walletType: "Safe",
    kind: "vault",
    valueUsd: 960_000,
    change24hPct: 0.1,
    liquidityBucket: "T+1",
    riskLevel: "medium",
    notes: "Secondary yield sleeve with similar governance concentration.",
    tags: ["stablecoin", "protocol", "yield"],
    source: "Seeded ERC-4626 position",
    updatedAt: "Jul 16, 2026 09:25 UTC",
    underlying: "DAI",
  },
  aaveUsdc: {
    id: "aave-usdc",
    asset: "USDC",
    issuer: "Circle",
    chain: "Ethereum",
    venue: "Aave v3",
    wallet: "Yield Safe",
    walletType: "Safe",
    kind: "lending",
    valueUsd: 1_280_000,
    change24hPct: 0,
    liquidityBucket: "T+1",
    riskLevel: "medium",
    notes: "Earns idle yield but exit speed degrades when utilization spikes.",
    tags: ["stablecoin", "protocol", "circle", "yield"],
    source: "Seeded protocol position",
    updatedAt: "Jul 16, 2026 09:24 UTC",
  },
  ethCollateral: {
    id: "eth-collateral",
    asset: "ETH",
    issuer: "Native",
    chain: "Ethereum",
    venue: "Aave v3",
    wallet: "Ops Collateral",
    walletType: "Safe",
    kind: "collateral",
    valueUsd: 710_000,
    change24hPct: -2.6,
    liquidityBucket: "T+3",
    riskLevel: "high",
    notes: "Volatile collateral supporting a smaller operating credit line.",
    tags: ["protocol", "volatile", "collateral", "breach"],
    source: "Seeded protocol position",
    updatedAt: "Jul 16, 2026 09:24 UTC",
    healthFactor: 1.31,
  },
} satisfies Record<string, Position>

const steady: ScenarioSnapshot = {
  key: "steady",
  label: "Steady State",
  banner:
    "Seeded demo only. Holdings, prices, and policy outcomes are illustrative and not connected to live wallets.",
  incident:
    "Treasury is fundable today, but immediate liquidity remains under policy floor and Circle concentration is still too high.",
  asOf: "Jul 16, 2026 09:32 UTC",
  syncedAt: "2m behind chain head",
  metrics: {
    treasuryUsd: 12_220_000,
    t0Usd: 7_030_000,
    t1Usd: 11_510_000,
    monthlyBurnUsd: 800_000,
    totalRunwayMonths: 15.3,
    immediateRunwayMonths: 8.8,
    policyBreaches: 2,
    atRiskUsd: 2_190_000,
    netChange24hPct: -0.6,
    coveragePct: 98.6,
    wallets: 6,
    chains: 5,
  },
  trend: [
    { label: "May 29", totalRunway: 16.4, immediateRunway: 9.8, policyFloor: 9 },
    { label: "Jun 05", totalRunway: 16.1, immediateRunway: 9.5, policyFloor: 9 },
    { label: "Jun 12", totalRunway: 15.9, immediateRunway: 9.3, policyFloor: 9 },
    { label: "Jun 19", totalRunway: 15.8, immediateRunway: 9.1, policyFloor: 9 },
    { label: "Jun 26", totalRunway: 15.7, immediateRunway: 9.2, policyFloor: 9 },
    { label: "Jul 03", totalRunway: 15.6, immediateRunway: 9, policyFloor: 9 },
    { label: "Jul 10", totalRunway: 15.4, immediateRunway: 8.9, policyFloor: 9 },
    { label: "Jul 16", totalRunway: 15.3, immediateRunway: 8.8, policyFloor: 9 },
  ],
  liquidity: [
    { label: "T+0", valueUsd: 7_030_000, settlement: "0-4h", haircut: "0-1%" },
    { label: "T+1", valueUsd: 11_510_000, settlement: "by next business day", haircut: "1-3%" },
    { label: "T+3", valueUsd: 12_220_000, settlement: "with protocol unwinds", haircut: "3-7%" },
  ],
  positions: [
    clonePosition(basePositions.safeEthUsdc),
    clonePosition(basePositions.safeBaseUsdc),
    clonePosition(basePositions.tronUsdt),
    clonePosition(basePositions.solUsdc),
    clonePosition(basePositions.susdsVault),
    clonePosition(basePositions.sdaiVault),
    clonePosition(basePositions.aaveUsdc),
    clonePosition(basePositions.ethCollateral),
  ],
  policies: [
    {
      id: "issuer-circle",
      name: "Single issuer concentration",
      owner: "Treasury Lead",
      target: "<= 45% of treasury",
      current: "54.7% in Circle-linked exposure",
      status: "breach",
      note: "Most liquid balances still sit in Circle-linked assets across Ethereum, Base, Solana, and Aave.",
    },
    {
      id: "liquidity-floor",
      name: "Immediate runway floor",
      owner: "Finance Ops",
      target: ">= 9.0 months T+0",
      current: "8.8 months",
      status: "breach",
      note: "Payroll prefunding and market-maker float keep same-day reserves under the policy floor.",
    },
    {
      id: "protocol-cap",
      name: "Protocol deployment cap",
      owner: "Treasury Committee",
      target: "<= 40% of treasury",
      current: "36.7%",
      status: "pass",
      note: "Yield sleeves are meaningful but still inside the approved gross deployment range.",
    },
    {
      id: "secondary-chain",
      name: "Non-primary chain concentration",
      owner: "Finance Ops",
      target: "<= 45% of treasury",
      current: "30.2%",
      status: "pass",
      note: "Secondary chain balances are material but not dominant.",
    },
    {
      id: "counterparty-screening",
      name: "High-risk unscreened counterparties",
      owner: "Compliance",
      target: "0 active",
      current: "0 active",
      status: "pass",
      note: "No current hard blocks, but the Tron float wallet remains under closer review.",
    },
  ],
  alerts: [
    {
      id: "alert-liquidity-floor",
      title: "Immediate runway remains below the floor",
      detail: "T+0 months dipped under the 9.0 policy line after payroll prefunding.",
      severity: "high",
      source: "Policy engine",
      time: "18m ago",
    },
    {
      id: "alert-reserve",
      title: "Circle reserve evidence refreshed",
      detail: "Weekly reserve disclosure is current, but still attested rather than real-time proof of reserve.",
      severity: "medium",
      source: "Reserve monitor",
      time: "4h ago",
    },
    {
      id: "alert-aave",
      title: "Aave USDC exits now route through the T+1 bucket",
      detail: "Utilization remains elevated enough that same-day exit assumptions would be optimistic.",
      severity: "medium",
      source: "Protocol monitor",
      time: "42m ago",
    },
  ],
  actions: [
    {
      id: "withdraw-aave",
      title: "Withdraw $750k from Aave into Ops Safe",
      summary: "Lift the T+0 runway back above policy before next payroll week.",
      severity: "high",
      owner: "Treasury Lead",
      signerPolicy: "3 of 5 signers on Ops Safe",
      delivery: "Export to Safe batch",
      impact: "+0.9 immediate runway months; reduces protocol deployment.",
      deltaT0Usd: 750_000,
      deltaIssuerPct: 0,
      breachesResolved: 1,
      tags: ["protocols", "breaches", "stablecoins"],
    },
    {
      id: "rebalance-circle",
      title: "Rotate $1.15m of Circle exposure into Sky and Pax-style reserves",
      summary: "Reduce issuer concentration without fully sacrificing same-day access.",
      severity: "high",
      owner: "Treasury Committee",
      signerPolicy: "Committee approval plus 3 of 5 signers",
      delivery: "Policy memo and staged wallet instructions",
      impact: "-9.4 percentage points of Circle concentration.",
      deltaT0Usd: -100_000,
      deltaIssuerPct: -9.4,
      breachesResolved: 1,
      tags: ["breaches", "stablecoins"],
    },
    {
      id: "tighten-tron",
      title: "Raise threshold on the Tron float wallet",
      summary: "Move the float wallet from 2/4 to 3/5 and enforce an allowlist for new payout routes.",
      severity: "medium",
      owner: "Security Lead",
      signerPolicy: "Policy-only change; no balance movement",
      delivery: "Safe guard / custody policy change",
      impact: "Reduces operational and screening risk without moving funds.",
      deltaT0Usd: 0,
      deltaIssuerPct: 0,
      breachesResolved: 0,
      tags: ["breaches", "all"],
    },
  ],
  sources: [
    {
      id: "source-onchain",
      name: "Wallet balances and signer state",
      category: "On-chain",
      updatedAt: "Jul 16, 2026 09:32 UTC",
      freshness: "2m behind chain head",
      confidence: "Confirmed",
      detail: "Seeded as if indexed from Safe Transaction Service-style events and traces with confirmation awareness.",
    },
    {
      id: "source-market",
      name: "Spot and mark prices",
      category: "Market",
      updatedAt: "Jul 16, 2026 09:33 UTC",
      freshness: "staleness budget: 60s in production",
      confidence: "Estimated",
      detail: "Seeded from CoinGecko-style prices with explicit last-updated semantics for derived treasury values.",
    },
    {
      id: "source-reserve",
      name: "Stablecoin reserve evidence",
      category: "Reserve",
      updatedAt: "Jul 13, 2026",
      freshness: "weekly disclosure, monthly assurance",
      confidence: "Attested",
      detail: "Backed by issuer transparency and reserve-attestation cadence rather than live wallet proofs alone.",
    },
    {
      id: "source-compliance",
      name: "Sanctions and address screening",
      category: "Compliance",
      updatedAt: "Jul 16, 2026 08:58 UTC",
      freshness: "rechecked on new flow patterns",
      confidence: "Screened",
      detail: "Seeded screening state with explicit refresh time because compliance outcomes age quickly.",
    },
    {
      id: "source-protocol",
      name: "Protocol exit and risk parameters",
      category: "Protocol",
      updatedAt: "Jul 16, 2026 09:05 UTC",
      freshness: "hourly refresh target",
      confidence: "Estimated",
      detail: "Protocol liquidity, governance, and health-factor assumptions are modeled separately from wallet balances.",
    },
  ],
}

const liquidityShock: ScenarioSnapshot = {
  key: "liquidityShock",
  label: "Liquidity Shock",
  banner:
    "Stress mode. Same balances, worse exit conditions. Haircuts and settlement delays are seeded, not live.",
  incident:
    "Protocol exit speed and market-making float reliability degrade together, pushing immediate liquidity well below policy.",
  asOf: "Jul 16, 2026 09:32 UTC",
  syncedAt: "stress pack recomputed from seeded assumptions",
  metrics: {
    treasuryUsd: 11_640_000,
    t0Usd: 5_460_000,
    t1Usd: 9_840_000,
    monthlyBurnUsd: 800_000,
    totalRunwayMonths: 14.6,
    immediateRunwayMonths: 6.8,
    policyBreaches: 3,
    atRiskUsd: 3_410_000,
    netChange24hPct: -2.4,
    coveragePct: 97.9,
    wallets: 6,
    chains: 5,
  },
  trend: [
    { label: "May 29", totalRunway: 15.6, immediateRunway: 8.9, policyFloor: 9 },
    { label: "Jun 05", totalRunway: 15.4, immediateRunway: 8.6, policyFloor: 9 },
    { label: "Jun 12", totalRunway: 15.2, immediateRunway: 8.4, policyFloor: 9 },
    { label: "Jun 19", totalRunway: 15.1, immediateRunway: 8.2, policyFloor: 9 },
    { label: "Jun 26", totalRunway: 15, immediateRunway: 7.9, policyFloor: 9 },
    { label: "Jul 03", totalRunway: 14.9, immediateRunway: 7.6, policyFloor: 9 },
    { label: "Jul 10", totalRunway: 14.8, immediateRunway: 7.2, policyFloor: 9 },
    { label: "Jul 16", totalRunway: 14.6, immediateRunway: 6.8, policyFloor: 9 },
  ],
  liquidity: [
    { label: "T+0", valueUsd: 5_460_000, settlement: "0-8h", haircut: "2-6%" },
    { label: "T+1", valueUsd: 9_840_000, settlement: "next day if venues normalize", haircut: "4-8%" },
    { label: "T+3", valueUsd: 11_640_000, settlement: "requires unwind queueing", haircut: "6-12%" },
  ],
  positions: [
    clonePosition(basePositions.safeEthUsdc, {
      valueUsd: 3_290_000,
      change24hPct: -0.4,
      riskLevel: "medium",
      notes: "Still liquid, but OTC routing assumptions widened.",
    }),
    clonePosition(basePositions.safeBaseUsdc, {
      valueUsd: 1_110_000,
      change24hPct: -0.6,
      riskLevel: "high",
      notes: "Secondary-chain exit depth is materially worse under this stress pack.",
    }),
    clonePosition(basePositions.tronUsdt, {
      valueUsd: 1_480_000,
      change24hPct: -0.3,
      riskLevel: "critical",
      notes: "Counterparty dependence and routing friction make this float less reliable.",
    }),
    clonePosition(basePositions.solUsdc, {
      valueUsd: 820_000,
      change24hPct: -0.5,
      riskLevel: "high",
      notes: "Payout lane still available, but only after haircut and lane prioritization.",
    }),
    clonePosition(basePositions.susdsVault, {
      valueUsd: 2_180_000,
      change24hPct: -0.2,
      riskLevel: "high",
      notes: "Still solvent, but redemption becomes part of tomorrow’s rather than today’s liquidity plan.",
      tags: ["stablecoin", "protocol", "yield", "protocols"],
    }),
    clonePosition(basePositions.sdaiVault, {
      valueUsd: 930_000,
      change24hPct: -0.2,
      riskLevel: "medium",
    }),
    clonePosition(basePositions.aaveUsdc, {
      valueUsd: 1_160_000,
      change24hPct: -0.4,
      riskLevel: "high",
      notes: "Utilization spike shifts this from same-day confidence to next-day planning.",
      tags: ["stablecoin", "protocol", "circle", "yield", "breach"],
    }),
    clonePosition(basePositions.ethCollateral, {
      valueUsd: 670_000,
      change24hPct: -6.8,
      healthFactor: 1.19,
      riskLevel: "critical",
      notes: "Volatility compresses collateral safety and raises liquidation sensitivity.",
    }),
  ],
  policies: [
    {
      id: "issuer-circle",
      name: "Single issuer concentration",
      owner: "Treasury Lead",
      target: "<= 45% of treasury",
      current: "54.7% in Circle-linked exposure",
      status: "breach",
      note: "Circle share is unchanged enough that the core issuer problem remains unresolved.",
    },
    {
      id: "liquidity-floor",
      name: "Immediate runway floor",
      owner: "Finance Ops",
      target: ">= 9.0 months T+0",
      current: "6.8 months",
      status: "breach",
      note: "This is now the largest control failure in the workspace.",
    },
    {
      id: "protocol-cap",
      name: "Protocol deployment cap",
      owner: "Treasury Committee",
      target: "<= 40% of treasury",
      current: "42.4%",
      status: "breach",
      note: "Once spot balances are haircut, deployed protocol capital becomes too dominant.",
    },
    {
      id: "secondary-chain",
      name: "Non-primary chain concentration",
      owner: "Finance Ops",
      target: "<= 45% of treasury",
      current: "29.3%",
      status: "pass",
      note: "Still within range, though its quality is worse than the raw share suggests.",
    },
    {
      id: "counterparty-screening",
      name: "High-risk unscreened counterparties",
      owner: "Compliance",
      target: "0 active",
      current: "1 wallet under enhanced review",
      status: "warn",
      note: "Falcon Float is not blocked, but routing confidence has degraded enough to escalate review.",
    },
  ],
  alerts: [
    {
      id: "alert-liquidity-shock",
      title: "Liquidity ladder degraded by 22%",
      detail: "Protocol exits no longer qualify for the same-day bucket in this scenario.",
      severity: "critical",
      source: "Scenario engine",
      time: "just now",
    },
    {
      id: "alert-health-factor",
      title: "ETH collateral health factor slipped to 1.19",
      detail: "Still above liquidation, but materially less forgiving if volatility continues.",
      severity: "critical",
      source: "Aave monitor",
      time: "11m ago",
    },
    {
      id: "alert-tron",
      title: "Tron float wallet elevated for manual review",
      detail: "Routing dependency now matters more than raw balance size.",
      severity: "high",
      source: "Compliance monitor",
      time: "23m ago",
    },
  ],
  actions: [
    {
      id: "withdraw-aave",
      title: "Pull $1.1m from Aave into Ops Safe over two batched exits",
      summary: "Primary way to recover immediate runway under this scenario.",
      severity: "critical",
      owner: "Treasury Lead",
      signerPolicy: "3 of 5 signers plus treasury committee notice",
      delivery: "Safe batch + protocol unwind runbook",
      impact: "+1.4 immediate runway months; reduces protocol exposure below cap.",
      deltaT0Usd: 1_100_000,
      deltaIssuerPct: 0,
      breachesResolved: 2,
      tags: ["protocols", "breaches", "stablecoins"],
    },
    {
      id: "rebalance-circle",
      title: "Rotate $900k of Circle exposure before the next payout wave",
      summary: "Reduce the issuer breach without taking the entire treasury out of liquid instruments.",
      severity: "high",
      owner: "Treasury Committee",
      signerPolicy: "Committee approval plus staged execution",
      delivery: "Rebalance memo and wallet instructions",
      impact: "-7.2 percentage points of Circle concentration.",
      deltaT0Usd: -50_000,
      deltaIssuerPct: -7.2,
      breachesResolved: 1,
      tags: ["stablecoins", "breaches"],
    },
    {
      id: "pause-tron-lane",
      title: "Cap the Tron float wallet at $1.0m until screening clears",
      summary: "Treat the float as an operational lane, not reserve capital.",
      severity: "high",
      owner: "Compliance",
      signerPolicy: "Policy-only plus desk acknowledgement",
      delivery: "Counterparty lane update",
      impact: "Improves confidence in the remaining T+0 pool.",
      deltaT0Usd: 0,
      deltaIssuerPct: -1.4,
      breachesResolved: 0,
      tags: ["breaches", "all"],
    },
  ],
  sources: [
    {
      id: "source-onchain",
      name: "Wallet balances and signer state",
      category: "On-chain",
      updatedAt: "Jul 16, 2026 09:32 UTC",
      freshness: "2m behind chain head",
      confidence: "Confirmed",
      detail: "Underlying balances are unchanged; only the stress pack changes how much is considered immediately usable.",
    },
    {
      id: "source-market",
      name: "Spot and mark prices",
      category: "Market",
      updatedAt: "Jul 16, 2026 09:33 UTC",
      freshness: "stress pack uses wider exit assumptions",
      confidence: "Estimated",
      detail: "This scenario prioritizes exit depth and haircut behavior over pure spot price moves.",
    },
    {
      id: "source-reserve",
      name: "Stablecoin reserve evidence",
      category: "Reserve",
      updatedAt: "Jul 13, 2026",
      freshness: "no new reserve impairment disclosed",
      confidence: "Attested",
      detail: "Reserve evidence is current enough for context, but still not live proof for intraday routing decisions.",
    },
    {
      id: "source-compliance",
      name: "Sanctions and address screening",
      category: "Compliance",
      updatedAt: "Jul 16, 2026 09:04 UTC",
      freshness: "enhanced review triggered",
      confidence: "Screened",
      detail: "Manual review was elevated because the Tron lane’s operational dependency increased.",
    },
    {
      id: "source-protocol",
      name: "Protocol exit and risk parameters",
      category: "Protocol",
      updatedAt: "Jul 16, 2026 09:09 UTC",
      freshness: "hourly refresh target",
      confidence: "Estimated",
      detail: "Aave utilization and collateral behavior drive the bulk of the scenario downgrade.",
    },
  ],
}

const usdcStress: ScenarioSnapshot = {
  key: "usdcStress",
  label: "USDC Stress",
  banner:
    "Issuer stress mode. Circle-linked balances are marked down and same-day assumptions are more conservative. Still seeded; not live.",
  incident:
    "A Circle-specific stress event widens the issuer breach, compresses same-day runway, and makes diversification the dominant treasury action.",
  asOf: "Jul 16, 2026 09:32 UTC",
  syncedAt: "stress pack recomputed from seeded assumptions",
  metrics: {
    treasuryUsd: 10_980_000,
    t0Usd: 4_330_000,
    t1Usd: 8_970_000,
    monthlyBurnUsd: 800_000,
    totalRunwayMonths: 13.7,
    immediateRunwayMonths: 5.4,
    policyBreaches: 4,
    atRiskUsd: 5_680_000,
    netChange24hPct: -5.8,
    coveragePct: 98.1,
    wallets: 6,
    chains: 5,
  },
  trend: [
    { label: "May 29", totalRunway: 15.9, immediateRunway: 9.2, policyFloor: 9 },
    { label: "Jun 05", totalRunway: 15.7, immediateRunway: 8.9, policyFloor: 9 },
    { label: "Jun 12", totalRunway: 15.4, immediateRunway: 8.6, policyFloor: 9 },
    { label: "Jun 19", totalRunway: 15.2, immediateRunway: 8.1, policyFloor: 9 },
    { label: "Jun 26", totalRunway: 14.9, immediateRunway: 7.7, policyFloor: 9 },
    { label: "Jul 03", totalRunway: 14.6, immediateRunway: 7.1, policyFloor: 9 },
    { label: "Jul 10", totalRunway: 14.2, immediateRunway: 6.2, policyFloor: 9 },
    { label: "Jul 16", totalRunway: 13.7, immediateRunway: 5.4, policyFloor: 9 },
  ],
  liquidity: [
    { label: "T+0", valueUsd: 4_330_000, settlement: "same day only after haircut", haircut: "3-9%" },
    { label: "T+1", valueUsd: 8_970_000, settlement: "next day under managed exits", haircut: "5-11%" },
    { label: "T+3", valueUsd: 10_980_000, settlement: "requires staged reserve changes", haircut: "8-15%" },
  ],
  positions: [
    clonePosition(basePositions.safeEthUsdc, {
      valueUsd: 3_020_000,
      change24hPct: -3.1,
      riskLevel: "critical",
      notes: "Still fundable, but direct Circle exposure is now the main issuer risk.",
      tags: ["stablecoin", "circle", "liquid", "breach"],
    }),
    clonePosition(basePositions.safeBaseUsdc, {
      valueUsd: 1_030_000,
      change24hPct: -3.4,
      riskLevel: "critical",
      notes: "Secondary-chain Circle exposure compounds issuer stress.",
      tags: ["stablecoin", "circle", "liquid", "secondary-chain", "breach"],
    }),
    clonePosition(basePositions.tronUsdt, {
      valueUsd: 1_600_000,
      change24hPct: -0.1,
      riskLevel: "high",
      notes: "Relative share rises as Circle-linked assets mark down.",
    }),
    clonePosition(basePositions.solUsdc, {
      valueUsd: 790_000,
      change24hPct: -3.5,
      riskLevel: "critical",
      notes: "Still an operational payout lane, but the issuer stress is now visible here too.",
      tags: ["stablecoin", "circle", "liquid", "secondary-chain", "breach"],
    }),
    clonePosition(basePositions.susdsVault, {
      valueUsd: 2_160_000,
      change24hPct: -0.3,
      riskLevel: "medium",
    }),
    clonePosition(basePositions.sdaiVault, {
      valueUsd: 940_000,
      change24hPct: -0.2,
      riskLevel: "medium",
    }),
    clonePosition(basePositions.aaveUsdc, {
      valueUsd: 810_000,
      change24hPct: -3.9,
      riskLevel: "critical",
      notes: "Circle-linked protocol capital now behaves like delayed exposure instead of reserve cash.",
      tags: ["stablecoin", "protocol", "circle", "yield", "breach"],
    }),
    clonePosition(basePositions.ethCollateral, {
      valueUsd: 630_000,
      change24hPct: -4.7,
      healthFactor: 1.17,
      riskLevel: "high",
    }),
  ],
  policies: [
    {
      id: "issuer-circle",
      name: "Single issuer concentration",
      owner: "Treasury Lead",
      target: "<= 45% of treasury",
      current: "51.3% in Circle-linked exposure",
      status: "breach",
      note: "Absolute value fell, but the concentration is still far too high for a stress period.",
    },
    {
      id: "liquidity-floor",
      name: "Immediate runway floor",
      owner: "Finance Ops",
      target: ">= 9.0 months T+0",
      current: "5.4 months",
      status: "breach",
      note: "The treasury is no longer comfortably inside the same-day funding range.",
    },
    {
      id: "protocol-cap",
      name: "Protocol deployment cap",
      owner: "Treasury Committee",
      target: "<= 40% of treasury",
      current: "41.2%",
      status: "breach",
      note: "Deployed protocol capital becomes too large once Circle-linked spot is marked down.",
    },
    {
      id: "secondary-chain",
      name: "Non-primary chain concentration",
      owner: "Finance Ops",
      target: "<= 45% of treasury",
      current: "31.1%",
      status: "pass",
      note: "Still within numeric bounds, though quality of liquidity is lower than the headline share suggests.",
    },
    {
      id: "counterparty-screening",
      name: "High-risk unscreened counterparties",
      owner: "Compliance",
      target: "0 active",
      current: "1 wallet under enhanced review",
      status: "warn",
      note: "Counterparty review is not the core breach, but it should not be ignored during issuer stress.",
    },
  ],
  alerts: [
    {
      id: "alert-usdc",
      title: "USDC stress pack active",
      detail: "Circle-linked balances are marked down and same-day reserve assumptions are reduced.",
      severity: "critical",
      source: "Scenario engine",
      time: "just now",
    },
    {
      id: "alert-circle-share",
      title: "Circle remains the dominant treasury issuer",
      detail: "Even after the markdown, issuer concentration remains materially above policy.",
      severity: "high",
      source: "Policy engine",
      time: "just now",
    },
    {
      id: "alert-usdc-protocol",
      title: "Circle-linked protocol capital no longer qualifies as reserve-quality cash",
      detail: "Aave USDC exposure is treated as delayed liquidity in this mode.",
      severity: "high",
      source: "Protocol monitor",
      time: "9m ago",
    },
  ],
  actions: [
    {
      id: "rebalance-circle",
      title: "Cut Circle-linked exposure by $1.8m over two treasury windows",
      summary: "This is the highest-leverage move because it clears both issuer concentration and same-day policy pressure.",
      severity: "critical",
      owner: "Treasury Committee",
      signerPolicy: "Committee approval plus staged signer execution",
      delivery: "Treasury rebalance package",
      impact: "-14.7 percentage points of Circle concentration.",
      deltaT0Usd: 200_000,
      deltaIssuerPct: -14.7,
      breachesResolved: 2,
      tags: ["stablecoins", "breaches"],
    },
    {
      id: "withdraw-aave",
      title: "Exit the remaining Circle-linked Aave sleeve",
      summary: "Protects same-day liquidity quality and lowers protocol dependency during issuer stress.",
      severity: "critical",
      owner: "Treasury Lead",
      signerPolicy: "3 of 5 signers on Yield Safe",
      delivery: "Protocol unwind runbook",
      impact: "+1.0 immediate runway months; clears protocol-cap breach if paired with the issuer rebalance.",
      deltaT0Usd: 810_000,
      deltaIssuerPct: -1.8,
      breachesResolved: 1,
      tags: ["protocols", "breaches", "stablecoins"],
    },
    {
      id: "tighten-tron",
      title: "Treat USDT float as temporary liquidity, not strategic reserve",
      summary: "Freeze growth in the float wallet while the team reassigns strategic reserves elsewhere.",
      severity: "medium",
      owner: "Compliance",
      signerPolicy: "Policy-only change",
      delivery: "Desk instruction and monitoring update",
      impact: "Prevents the fallback lane from becoming a hidden treasury anchor.",
      deltaT0Usd: 0,
      deltaIssuerPct: 0,
      breachesResolved: 0,
      tags: ["all", "breaches"],
    },
  ],
  sources: [
    {
      id: "source-onchain",
      name: "Wallet balances and signer state",
      category: "On-chain",
      updatedAt: "Jul 16, 2026 09:32 UTC",
      freshness: "2m behind chain head",
      confidence: "Confirmed",
      detail: "Wallet balances are still block-confirmed; this scenario changes how safe those balances are to rely on.",
    },
    {
      id: "source-market",
      name: "Spot and mark prices",
      category: "Market",
      updatedAt: "Jul 16, 2026 09:33 UTC",
      freshness: "staleness budget: 60s in production",
      confidence: "Estimated",
      detail: "Circle-linked marks are scenario-adjusted and visibly separate from raw balance availability.",
    },
    {
      id: "source-reserve",
      name: "Stablecoin reserve evidence",
      category: "Reserve",
      updatedAt: "Jul 13, 2026",
      freshness: "no live reserve shortfall disclosed",
      confidence: "Attested",
      detail: "Attested backing remains important context, but it does not eliminate intraday treasury routing risk.",
    },
    {
      id: "source-compliance",
      name: "Sanctions and address screening",
      category: "Compliance",
      updatedAt: "Jul 16, 2026 09:04 UTC",
      freshness: "unchanged since last rescan",
      confidence: "Screened",
      detail: "Screening is stable, but secondary market monitoring is still relevant under stablecoin stress.",
    },
    {
      id: "source-protocol",
      name: "Protocol exit and risk parameters",
      category: "Protocol",
      updatedAt: "Jul 16, 2026 09:09 UTC",
      freshness: "hourly refresh target",
      confidence: "Estimated",
      detail: "Protocol positions remain operationally usable, but they no longer qualify as reserve-quality cash in this mode.",
    },
  ],
}

export const demoWorkspace: DemoWorkspace = {
  name: "Helm Treasury",
  entity: "Northstar Foundation Treasury",
  signers: 5,
  chains: ["Ethereum", "Base", "Solana", "Tron", "Aave v3"],
  policyTemplate: "Stable reserve + payroll continuity",
  upcoming: [
    "Payroll batch due in 2 days: $640k",
    "Market-maker top-up review in 3 days: cap $1.0m",
    "Foundation grant disbursement next week: $420k",
  ],
  onboarding: [
    "Import the first Safe or watch-only wallet.",
    "Set monthly burn and upcoming obligations.",
    "Choose a treasury policy template.",
    "Review the first queued rebalance package before signers touch funds.",
  ],
  scenarios: {
    steady,
    liquidityShock,
    usdcStress,
  },
}
