export const cv = {
  name: "Ricardo Jorge", monogram: "RJ", role: "AI Product Engineer", location: "Lisbon, Portugal", email: "ricardojorgexyz@gmail.com",
  links: [["cv.rj11.io", "https://cv.rj11.io"], ["rj11.io", "https://rj11.io"], ["github.com/rj11io", "https://github.com/rj11io"], ["linkedin.com/in/rj11io", "https://linkedin.com/in/rj11io"]] as const,
  summary: "AI product engineer with a decade of professional TypeScript experience, building on React since 2016 and Next.js since 2018. Often the first frontend hire, owning architecture, tooling, component libraries, and delivery pipelines - then growing the team around them.",
  focus: "Builds dashboards, product platforms, and proprietary data explorers for cybersecurity, crypto, gaming, and early-stage B2B teams. Brings product engineering, data visualisation, and AI agent harnesses together from first commit to shipped workflow.",
  skills: [["Core stack", "TypeScript · React.js · Next.js · AI SDK · Convex · Playwright · Vercel"], ["AI engineering", "Agent automations · Custom agent skills · Harness engineering · Codex · Claude Code · n8n"], ["UI & data", "Tailwind CSS · shadcn/ui · Design systems · Storybook · Dashboards · d3 · Recharts · Nivo"], ["Leadership", "Team & project management · End-to-end product delivery · Product design · Agile methodologies"]],
  projects: [["11io", "rj11.io", "Personal brand for B2B freelancing", "2025 - Present", "https://rj11.io"], ["11ai", "ai.rj11.io", "Open-source AI skills, plugins, and workflows", "2026 - Present", "https://ai.rj11.io"], ["11bench", "bench.rj11.io", "Open-source AI benchmarks", "2026 - Present", "https://bench.rj11.io"]] as const,
  experience: [
    { role: "AI Product Engineer", company: "rj11io", site: "rj11.io", dates: "Mar 2025 - Present", note: "B2B · Remote", bullets: ["Hands-on AI product engineering for multiple early-stage startups, building projects from the ground up.", "AI data extraction from PDFs, AI SEO analytics, a GenAI dermatopathology portal, real-estate platform, cybersecurity dashboards, and proprietary data explorers.", "AI chats and GPT experiences; agent harnesses, skills, automations, and n8n workflows."] },
    { role: "Product / Datavis Engineer", company: "Hunt Intelligence, Inc.", site: "hunt.io", dates: "Apr 2024 - Mar 2025", note: "B2B · Remote", bullets: ["Built core threat-intelligence modules AttackCapture™ and HuntSQL™ on a modern TypeScript codebase.", "Created custom data-visualisation components, including the IP History Widget.", "Shipped an OpenAPI-based documentation platform with enriched metadata and a friendlier UI than Swagger; built with Next.js, shadcn/ui, Playwright, Vercel, and GitHub Actions."] },
    { role: "Senior Frontend Engineer → Team Lead", company: "OMEGA Systems", site: "omegasys.eu", dates: "Jun 2023 - Apr 2024", note: "Remote", bullets: ["Built the next-generation CORE5 iGaming platform management system with TypeScript and React; promoted to lead the frontend team.", "Delivered dashboard visualisation, reporting, configuration, localisation, and internal tab-system features.", "Built the developer onboarding experience and set standards for tickets, documentation, async workflows, and Definition of Done."] },
    { role: "Senior Frontend Engineer", company: "Phantasma Chain", site: "phantasma.info", dates: "Jan 2022 - May 2023", note: "Remote", bullets: ["Built a frontend monorepo for new tools and apps, the Phantasma UI Storybook, and Phantasma Explorer.", "Established Playwright tests, GitHub Actions CI, Vercel CD, localisation, white-label theming, and environment configuration.", "Contributed improvements to the Phantasma TypeScript SDK and built supporting React hooks, APIs, scripts, and tooling."] },
    { role: "Frontend Lead", company: "BinaryEdge · Coalition, Inc.", site: "coalitioninc.com", dates: "Feb 2020 - Oct 2021", note: "Remote", bullets: ["Started as a solo frontend engineer and grew a team focused on customer-facing security apps and internal tools.", "Introduced React, TypeScript, Next.js, micro frontends, and a component-library practice; tech lead for Coalition Explorer and data visualisations.", "Built Attack Surface Monitoring for the BinaryEdge Portal, later integrated into Coalition Explorer and Coalition Control; migrated CI/CD from Drone to GitHub Actions."] },
  ],
  earlier: "Fullstack Engineer / Co-Founder, Glaiveware (2018 - 2019) · React Native Developer, Sycret.ink (2017) · Full Stack JavaScript Developer, American Heart Association (2016) · Frontend Developer, NextBitt (2015 - 2016) · Java Developer, Science4you (2015)",
  education: "IT Systems Management and Programming · Escola Profissional de Tecnologia Digital · 2013 - 2016",
  fun: "Placed second nationally and reached the final four of the 2008 robotics world cup in China with LEGO Mindstorms. Started coding by modding and reverse-engineering games, building a MUGEN fighting game, and running dedicated game servers.",
} as const
