"use client"

import { useMemo, useState } from "react"
import { ArrowUpRight, Bell, Check, ChevronDown, CircleHelp, Clock3, Download, FileText, Gauge, LayoutDashboard, LockKeyhole, Menu, MoreHorizontal, ShieldAlert, WalletCards, X } from "lucide-react"
import s from "./page.module.css"

const riskItems = [
  { id: "usdc", sev: "Review", title: "USDC concentration", body: "64% of NAV is in one stablecoin", detail: "A single issuer now represents 64% of the vault. This is above your 50% concentration policy and is a diversification review—not a sell signal.", evidence: "Positions · 12:00 UTC · Chainalysis index", tone: "amber" },
  { id: "arb", sev: "Watch", title: "Arbitrum runway", body: "14 days at current operating outflow", detail: "Your liquid Arbitrum balance covers 14 days against a 21-day floor. The shortfall is driven by a proposed 4,500 USDC vendor payment.", evidence: "Policy engine · 12:00 UTC · high confidence", tone: "blue" },
  { id: "approval", sev: "Block", title: "New spender approval", body: "Unknown contract · 3 hours ago", detail: "A new token approval was observed from the operations multisig. The contract is not in your allowlist. Confirm its purpose before any signing.", evidence: "Safe event log · 09:12 UTC · medium confidence", tone: "coral" },
]

export default function Page() {
  const [section, setSection] = useState("Overview")
  const [range, setRange] = useState("7D")
  const [selected, setSelected] = useState<typeof riskItems[number] | null>(null)
  const [paymentOpen, setPaymentOpen] = useState(false)
  const [dismissed, setDismissed] = useState<string[]>([])
  const visibleRisks = useMemo(() => riskItems.filter((item) => !dismissed.includes(item.id)), [dismissed])
  return <main className={s.app}>
    <aside className={s.sidebar}><div className={s.brand}><span className={s.logo}>⌁</span><span>Cairn</span><span className={s.beta}>BETA</span></div><div className={s.vault}><span className={s.vaultIcon}>◈</span><div><b>Northstar DAO</b><small>Primary vault</small></div><ChevronDown size={15}/></div><nav>{["Overview", "Risk queue", "Reports", "Settings"].map((item, i) => <button key={item} className={section === item ? s.navActive : ""} onClick={() => setSection(item)}>{i === 0 ? <LayoutDashboard size={17}/> : i === 1 ? <ShieldAlert size={17}/> : i === 2 ? <FileText size={17}/> : <Gauge size={17}/>} {item}{item === "Risk queue" && visibleRisks.length > 0 && <em>{visibleRisks.length}</em>}</button>)}</nav><div className={s.sideBottom}><div className={s.demo}><span></span><div><b>Seeded demo</b><small>Snapshot · 12:00 UTC</small></div><CircleHelp size={15}/></div><div className={s.user}><div className={s.avatar}>JM</div><div><b>Jamie Moore</b><small>Admin · read-only</small></div><MoreHorizontal size={16}/></div></div></aside>
    <section className={s.content}><header className={s.header}><button className={s.mobileMenu}><Menu size={20}/></button><div><p className={s.eyebrow}>MONDAY, JUL 16, 2026 <span>•</span> MORNING BRIEF</p><h1>{section === "Overview" ? "Good morning, Jamie." : section}</h1><p className={s.subhead}>{section === "Overview" ? "Here’s what changed in Northstar’s treasury." : "This is a seeded product preview for your team."}</p></div><div className={s.headerActions}><button className={s.iconButton}><Bell size={18}/><i></i></button><button className={s.reportButton} onClick={() => setSection("Reports")}><Download size={16}/> Export brief</button></div></header>
      {section === "Reports" ? <ReportView/> : section === "Settings" ? <SettingsView/> : <>
      <div className={s.statusbar}><div><span className={s.greenDot}></span><b>All systems reconciled</b><span className={s.sep}>/</span> Last snapshot 12:00 UTC</div><span className={s.source}><span>Source</span> CoinGecko + Safe index <CircleHelp size={14}/></span></div>
      <div className={s.metrics}><Metric label="Total NAV" value="$1,248,620" change="+$18,420" percent="+1.50%" up/><Metric label="7D change" value="+$42,890" change="vs. prior period" percent="+3.56%" up/><Metric label="Liquid runway" value="38 days" change="Policy floor 21d" percent="Healthy"/><Metric label="Needs review" value={visibleRisks.length.toString().padStart(2, "0")} change="1 block · 2 watch" percent="Open queue" alert/></div>
      <div className={s.grid}><section className={s.card + " " + s.chartCard}><div className={s.cardHead}><div><p className={s.kicker}>TREASURY VALUE</p><h2>NAV over time</h2></div><div className={s.range}>{["7D", "30D"].map(x => <button key={x} onClick={() => setRange(x)} className={range === x ? s.rangeActive : ""}>{x}</button>)}</div></div><div className={s.chartMeta}><span><b>$1.24m</b> current NAV</span><span className={s.positive}><ArrowUpRight size={15}/> 3.56% {range}</span></div><svg viewBox="0 0 700 220" className={s.chart} role="img" aria-label="Illustrative NAV chart rising from 1.20m to 1.24m"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#7bbfa4" stopOpacity=".26"/><stop offset="1" stopColor="#7bbfa4" stopOpacity="0"/></linearGradient></defs><path d="M0 178 C70 168 88 172 142 151 S220 165 270 130 S347 139 392 110 S458 122 505 90 S590 97 700 32 L700 220 L0 220Z" fill="url(#fill)"/><path d="M0 178 C70 168 88 172 142 151 S220 165 270 130 S347 139 392 110 S458 122 505 90 S590 97 700 32" fill="none" stroke="#287b67" strokeWidth="3"/><line x1="0" y1="205" x2="700" y2="205" stroke="#d9d8d0" strokeDasharray="4 5"/><text x="4" y="218" fill="#8b8c86" fontSize="10">$1.20m</text><text x="650" y="218" fill="#8b8c86" fontSize="10">Today</text></svg><div className={s.chartFoot}><span>Illustrative snapshot · values are fictional</span><span>USD · UTC</span></div></section>
      <section className={s.card + " " + s.allocation}><div className={s.cardHead}><div><p className={s.kicker}>WHERE IT SITS</p><h2>Allocation</h2></div><button className={s.textButton}>View all <ArrowUpRight size={14}/></button></div><div className={s.allocTotal}><b>$1,248,620</b><span>Total NAV</span></div>{[{n:"Stablecoins",v:"$801,120",p:64,c:"#5a9b81"},{n:"ETH",v:"$278,240",p:22,c:"#7d82c6"},{n:"BTC",v:"$106,130",p:9,c:"#d49a53"},{n:"Other",v:"$63,130",p:5,c:"#a9aaa2"}].map(x => <div className={s.allocRow} key={x.n}><div><span className={s.swatch} style={{background:x.c}}></span><b>{x.n}</b><span>{x.v}</span></div><strong>{x.p}%</strong><div className={s.bar}><i style={{width:x.p+"%", background:x.c}}></i></div></div>)}<div className={s.policyNote}><ShieldAlert size={16}/><span><b>Policy note</b> Stablecoin concentration is above your 50% threshold.</span></div></section>
      <section className={s.card + " " + s.riskCard}><div className={s.cardHead}><div><p className={s.kicker}>ACTION QUEUE</p><h2>Needs review <span className={s.count}>{visibleRisks.length}</span></h2></div><button className={s.textButton} onClick={() => setSection("Risk queue")}>Open queue <ArrowUpRight size={14}/></button></div>{visibleRisks.map(x => <button className={s.riskRow} key={x.id} onClick={() => setSelected(x)}><span className={s.riskIcon + " " + s[x.tone]}>{x.tone === "coral" ? <LockKeyhole size={15}/> : <ShieldAlert size={15}/>}</span><span><b>{x.title}</b><small>{x.body}</small></span><span className={s.severity + " " + s[x.tone]}>{x.sev}</span><ArrowUpRight size={16}/></button>)}{!visibleRisks.length && <div className={s.empty}><Check size={20}/> Queue cleared for this snapshot.</div>}</section>
      <section className={s.card + " " + s.payCard}><div className={s.payIcon}><WalletCards size={21}/></div><div><p className={s.kicker}>DECISION CHECK</p><h2>Can we pay?</h2><p>Check a proposed payment against liquid balance and your runway policy.</p></div><button className={s.primary} onClick={() => setPaymentOpen(true)}>Run a check <ArrowUpRight size={15}/></button></section>
      </div></>}
    </section>
    {selected && <div className={s.overlay} onClick={() => setSelected(null)}><aside className={s.drawer} onClick={e => e.stopPropagation()}><button className={s.close} onClick={() => setSelected(null)}><X size={18}/></button><span className={s.severity + " " + s[selected.tone]}>{selected.sev}</span><h2>{selected.title}</h2><p className={s.drawerLead}>{selected.detail}</p><div className={s.evidence}><p className={s.kicker}>EVIDENCE</p><b>{selected.evidence}</b><span>Snapshot values are fictional and read-only.</span></div><h3>Suggested next action</h3><p>Confirm the underlying wallet or policy context with your security owner before making a change.</p><button className={s.secondary} onClick={() => {setDismissed([...dismissed, selected.id]); setSelected(null)}}>Mark reviewed <Check size={15}/></button></aside></div>}
    {paymentOpen && <div className={s.overlay} onClick={() => setPaymentOpen(false)}><div className={s.modal} onClick={e => e.stopPropagation()}><button className={s.close} onClick={() => setPaymentOpen(false)}><X size={18}/></button><p className={s.kicker}>PAYMENT READINESS</p><h2>Check a proposed payment</h2><label>Amount (USD)<input defaultValue="4500" /></label><label>Destination chain<select defaultValue="Arbitrum"><option>Arbitrum</option><option>Ethereum</option></select></label><div className={s.checkResult}><span className={s.amberDot}></span><div><b>Review required</b><small>After payment: 31 liquid runway days. Above 21-day floor, but Arbitrum is below policy target.</small></div></div><button className={s.primary + " " + s.full} onClick={() => setPaymentOpen(false)}>Done</button></div></div>}
  </main>
}

function Metric({label,value,change,percent,up,alert}:{label:string,value:string,change:string,percent:string,up?:boolean,alert?:boolean}) { return <div className={s.metric}><p>{label} {alert && <span className={s.alertDot}>!</span>}</p><b>{value}</b><div><span className={up ? s.positive : alert ? s.amber : ""}>{up && <ArrowUpRight size={14}/>} {percent}</span><small>{change}</small></div></div> }
function ReportView(){ return <div className={s.report}><div className={s.reportHero}><div><p className={s.kicker}>SHAREABLE EVIDENCE</p><h2>Northstar treasury brief</h2><p>Prepared from the seeded snapshot on Jul 16, 2026 at 12:00 UTC.</p></div><button className={s.primary}><Download size={15}/> Download preview</button></div><div className={s.card + " " + s.reportSheet}><p className={s.kicker}>EXECUTIVE SUMMARY</p><h2>Stablecoin concentration is the main conversation.</h2><p>Northstar is above its stablecoin policy threshold, while overall liquid runway remains above the floor. One unknown approval requires security-owner review before signing.</p><div className={s.reportStats}><b>$1.24m<small>Total NAV</small></b><b>38d<small>Liquid runway</small></b><b>3<small>Open reviews</small></b></div><div className={s.policyNote}><Clock3 size={16}/> Snapshot only · fictional values · no live wallet or market connection</div></div></div> }
function SettingsView(){ return <div className={s.settings}><div className={s.card}><p className={s.kicker}>VAULT SETTINGS</p><h2>Policy guardrails</h2><p className={s.subhead}>These demo preferences persist on this device.</p><label>Minimum runway floor (days)<input defaultValue="21" /></label><label>Stablecoin concentration threshold (%)<input defaultValue="50" /></label><button className={s.primary}><Check size={15}/> Saved locally</button></div><div className={s.card}><p className={s.kicker}>ACCESS</p><h2>Read-only by default</h2><p>No wallet credentials, private keys, or signing permissions are requested in Cairn’s demo.</p><div className={s.policyNote}><LockKeyhole size={16}/> Production access would be scoped, encrypted, and audited.</div></div></div> }
