export type ScenarioId = "base" | "volatile" | "depeg" | "bridge"
export type WindowId = "7d" | "30d"
export type Severity = "clear" | "watch" | "high" | "critical" | "unknown"
export type Confidence = "high" | "medium" | "low" | "unknown"

export const asOf = "2026-07-16T08:30:00Z"

export const scenarios: Array<{
  id: ScenarioId
  label: string
  short: string
  description: string
  liquidityFactor: number
  confidencePenalty: number
  bps: Record<string, number>
}> = [
  {
    id: "base",
    label: "Base",
    short: "Base",
    description: "Current seeded operating view with normal liquidity.",
    liquidityFactor: 1,
    confidencePenalty: 0,
    bps: { USDC: 4, USDT: 8, EURC: 5, PYUSD: 6 },
  },
  {
    id: "volatile",
    label: "Volatile market",
    short: "Volatile",
    description: "Liquidity capacity reduced and slippage elevated.",
    liquidityFactor: 0.72,
    confidencePenalty: 6,
    bps: { USDC: 14, USDT: 28, EURC: 16, PYUSD: 18 },
  },
  {
    id: "depeg",
    label: "Stablecoin stress",
    short: "Depeg",
    description: "Issuer stress test with widened peg deviations.",
    liquidityFactor: 0.58,
    confidencePenalty: 12,
    bps: { USDC: 38, USDT: 95, EURC: 32, PYUSD: 44 },
  },
  {
    id: "bridge",
    label: "Bridge incident",
    short: "Bridge",
    description: "Bridge route degraded; same-chain liquidity preferred.",
    liquidityFactor: 0.66,
    confidencePenalty: 10,
    bps: { USDC: 10, USDT: 18, EURC: 12, PYUSD: 14 },
  },
]

export const entities = [
  { id: "all", name: "All entities", region: "Consolidated" },
  { id: "us-payments", name: "Northstar Payments US", region: "US" },
  { id: "eu-ops", name: "Northstar EU Ops", region: "EU" },
  { id: "foundation", name: "Northstar Foundation", region: "Global" },
]

export const positions = [
  {
    id: "pos-1",
    entityId: "us-payments",
    wallet: "Polygon payout hot",
    address: "0x91f2...c8a4",
    custody: "Fireblocks vault",
    asset: "USDC",
    issuer: "Circle",
    chain: "Polygon",
    venue: "Payout wallet",
    amountUsd: 1840000,
    eligibleUsd: 1600000,
    reserveAgeDays: 18,
    jurisdiction: "US permitted issuer watch",
    confidence: "high" as Confidence,
    source: "Seeded wallet indexer snapshot",
    block: "Polygon #73482844",
  },
  {
    id: "pos-2",
    entityId: "us-payments",
    wallet: "Ethereum cold reserve",
    address: "0x34b8...91d2",
    custody: "Safe 3-of-5",
    asset: "USDC",
    issuer: "Circle",
    chain: "Ethereum",
    venue: "Self-custody",
    amountUsd: 4200000,
    eligibleUsd: 2520000,
    reserveAgeDays: 18,
    jurisdiction: "US permitted issuer watch",
    confidence: "high" as Confidence,
    source: "Seeded Safe balance export",
    block: "Ethereum #22841892",
  },
  {
    id: "pos-3",
    entityId: "eu-ops",
    wallet: "Base merchant float",
    address: "0xc6d0...13aa",
    custody: "MPC custodian",
    asset: "USDC",
    issuer: "Circle",
    chain: "Base",
    venue: "Custody sub-account",
    amountUsd: 1120000,
    eligibleUsd: 980000,
    reserveAgeDays: 18,
    jurisdiction: "EU CASP support review",
    confidence: "medium" as Confidence,
    source: "Seeded custodian statement",
    block: "Base #32992115",
  },
  {
    id: "pos-4",
    entityId: "eu-ops",
    wallet: "EU settlement",
    address: "0x7e21...2b90",
    custody: "Banking partner wallet",
    asset: "EURC",
    issuer: "Circle",
    chain: "Ethereum",
    venue: "Banking partner",
    amountUsd: 860000,
    eligibleUsd: 720000,
    reserveAgeDays: 21,
    jurisdiction: "EU EMT authorized source required",
    confidence: "medium" as Confidence,
    source: "Seeded banking partner CSV",
    block: "Ethereum #22841892",
  },
  {
    id: "pos-5",
    entityId: "foundation",
    wallet: "Arbitrum grants",
    address: "0x44d1...71ff",
    custody: "Safe 4-of-7",
    asset: "USDT",
    issuer: "Tether",
    chain: "Arbitrum",
    venue: "Program wallet",
    amountUsd: 1380000,
    eligibleUsd: 1280000,
    reserveAgeDays: 41,
    jurisdiction: "Issuer disclosure age watch",
    confidence: "medium" as Confidence,
    source: "Seeded chain indexer",
    block: "Arbitrum #354920443",
  },
  {
    id: "pos-6",
    entityId: "foundation",
    wallet: "Exchange operating",
    address: "Internal account",
    custody: "Centralized exchange",
    asset: "USDT",
    issuer: "Tether",
    chain: "Exchange ledger",
    venue: "CEX venue",
    amountUsd: 940000,
    eligibleUsd: 700000,
    reserveAgeDays: 41,
    jurisdiction: "Off-chain statement",
    confidence: "low" as Confidence,
    source: "Seeded exchange export",
    block: "Statement 2026-07-16 07:00 UTC",
  },
  {
    id: "pos-7",
    entityId: "us-payments",
    wallet: "Solana pilot",
    address: "HN2f...9kQp",
    custody: "Pilot wallet",
    asset: "PYUSD",
    issuer: "Paxos",
    chain: "Solana",
    venue: "Payout wallet",
    amountUsd: 510000,
    eligibleUsd: 390000,
    reserveAgeDays: 27,
    jurisdiction: "US regulated issuer",
    confidence: "medium" as Confidence,
    source: "Seeded pilot ledger",
    block: "Solana slot 351882942",
  },
]

export const obligations = [
  {
    id: "obl-1",
    entityId: "us-payments",
    rail: "Polygon USDC merchant payouts",
    asset: "USDC",
    chain: "Polygon",
    due7Usd: 1280000,
    due30Usd: 3610000,
    source: "Seeded payout batch file",
  },
  {
    id: "obl-2",
    entityId: "eu-ops",
    rail: "Ethereum EURC supplier settlement",
    asset: "EURC",
    chain: "Ethereum",
    due7Usd: 620000,
    due30Usd: 1520000,
    source: "Seeded ERP export",
  },
  {
    id: "obl-3",
    entityId: "eu-ops",
    rail: "Base USDC marketplace refunds",
    asset: "USDC",
    chain: "Base",
    due7Usd: 520000,
    due30Usd: 1880000,
    source: "Seeded refund schedule",
  },
  {
    id: "obl-4",
    entityId: "foundation",
    rail: "Arbitrum USDT grants",
    asset: "USDT",
    chain: "Arbitrum",
    due7Usd: 1180000,
    due30Usd: 1980000,
    source: "Seeded grants calendar",
  },
  {
    id: "obl-5",
    entityId: "us-payments",
    rail: "Solana PYUSD beta payouts",
    asset: "PYUSD",
    chain: "Solana",
    due7Usd: 300000,
    due30Usd: 640000,
    source: "Seeded pilot batch",
  },
]

export const routes = [
  {
    id: "route-1",
    entityId: "us-payments",
    from: "Ethereum cold reserve",
    to: "Polygon payout hot",
    asset: "USDC",
    path: "Ethereum -> Polygon via custodian native transfer",
    capacityUsd: 1150000,
    slippageBps: 8,
    eta: "35m",
    limit: "Policy limit $1.2m/day",
    confidence: "high" as Confidence,
    source: "Seeded custodian route quote",
    bridgeSensitive: true,
  },
  {
    id: "route-2",
    entityId: "eu-ops",
    from: "Ethereum EU settlement",
    to: "Base merchant float",
    asset: "USDC",
    path: "Ethereum -> Base bridge route",
    capacityUsd: 620000,
    slippageBps: 18,
    eta: "52m",
    limit: "Bridge cap $750k/day",
    confidence: "medium" as Confidence,
    source: "Seeded bridge capacity model",
    bridgeSensitive: true,
  },
  {
    id: "route-3",
    entityId: "foundation",
    from: "Exchange operating",
    to: "Arbitrum grants",
    asset: "USDT",
    path: "CEX withdrawal -> Arbitrum",
    capacityUsd: 420000,
    slippageBps: 22,
    eta: "2h 10m",
    limit: "Venue withdrawal limit",
    confidence: "low" as Confidence,
    source: "Seeded exchange export",
    bridgeSensitive: false,
  },
  {
    id: "route-4",
    entityId: "us-payments",
    from: "Exchange RFQ",
    to: "Solana pilot",
    asset: "PYUSD",
    path: "OTC RFQ -> Solana",
    capacityUsd: 280000,
    slippageBps: 31,
    eta: "Same day",
    limit: "Insufficient quote depth above $280k",
    confidence: "unknown" as Confidence,
    source: "Seeded quote placeholder",
    bridgeSensitive: false,
  },
]

export const riskSignals = [
  {
    id: "sig-1",
    entityId: "foundation",
    title: "USDT issuer concentration above policy",
    target: "Foundation treasury",
    severity: { base: "high", volatile: "high", depeg: "critical", bridge: "high" } as Record<
      ScenarioId,
      Severity
    >,
    owner: "Controller",
    status: "Open",
    firstSeen: "2026-07-15 19:20 UTC",
    detail: "USDT is 63% of foundation liquid treasury; policy threshold is 45%.",
    evidence: "Seeded policy engine",
  },
  {
    id: "sig-2",
    entityId: "eu-ops",
    title: "EU stablecoin authorization evidence incomplete",
    target: "EURC supplier settlement",
    severity: { base: "watch", volatile: "watch", depeg: "high", bridge: "watch" } as Record<
      ScenarioId,
      Severity
    >,
    owner: "Compliance",
    status: "Open",
    firstSeen: "2026-07-16 05:15 UTC",
    detail: "CASP support status needs evidence before expanding EU settlement volume.",
    evidence: "Seeded compliance import",
  },
  {
    id: "sig-3",
    entityId: "us-payments",
    title: "Solana pilot route has insufficient quote depth",
    target: "PYUSD beta payouts",
    severity: {
      base: "watch",
      volatile: "high",
      depeg: "high",
      bridge: "watch",
    } as Record<ScenarioId, Severity>,
    owner: "Treasury Ops",
    status: "Open",
    firstSeen: "2026-07-16 07:45 UTC",
    detail: "RFQ depth covers only $280k of the 30-day pilot need.",
    evidence: "Seeded liquidity model",
  },
  {
    id: "sig-4",
    entityId: "us-payments",
    title: "Polygon payout wallet coverage healthy",
    target: "Polygon USDC",
    severity: {
      base: "clear",
      volatile: "watch",
      depeg: "watch",
      bridge: "watch",
    } as Record<ScenarioId, Severity>,
    owner: "Treasury Ops",
    status: "Reviewed",
    firstSeen: "2026-07-16 06:00 UTC",
    detail: "Same-chain funds cover the next 7-day payout batch before policy reserve.",
    evidence: "Seeded wallet indexer snapshot",
  },
]

export const evidenceItems = [
  {
    id: "ev-1",
    label: "Wallet balances reconciled",
    source: "Seeded indexer + custodian exports",
    timestamp: "2026-07-16 08:30 UTC",
    confidence: "high" as Confidence,
  },
  {
    id: "ev-2",
    label: "Reference prices and peg stress model",
    source: "Seeded market data model",
    timestamp: "2026-07-16 08:20 UTC",
    confidence: "medium" as Confidence,
  },
  {
    id: "ev-3",
    label: "Liquidity route capacities",
    source: "Seeded order-book, venue, and bridge assumptions",
    timestamp: "2026-07-16 08:10 UTC",
    confidence: "medium" as Confidence,
  },
  {
    id: "ev-4",
    label: "Sanctions and compliance review status",
    source: "Seeded compliance import",
    timestamp: "2026-07-16 07:55 UTC",
    confidence: "low" as Confidence,
  },
  {
    id: "ev-5",
    label: "Stablecoin reserve report age",
    source: "Seeded issuer metadata",
    timestamp: "Reports aged 18-41 days",
    confidence: "medium" as Confidence,
  },
]

export const runwaySeries = [
  { day: "Jul 16", base: 24, volatile: 21, depeg: 18, bridge: 20 },
  { day: "Jul 20", base: 23, volatile: 19, depeg: 16, bridge: 18 },
  { day: "Jul 24", base: 21, volatile: 17, depeg: 14, bridge: 16 },
  { day: "Jul 28", base: 19, volatile: 15, depeg: 12, bridge: 14 },
  { day: "Aug 01", base: 18, volatile: 13, depeg: 10, bridge: 12 },
  { day: "Aug 05", base: 17, volatile: 12, depeg: 9, bridge: 11 },
  { day: "Aug 09", base: 16, volatile: 11, depeg: 8, bridge: 10 },
  { day: "Aug 14", base: 15, volatile: 10, depeg: 7, bridge: 9 },
]

